### ISSUE TITLE
Could you provide an example on how to remove a delegate?

### ISSUE THREAD

**Issue by lumalav** [SamuelEnglard/weakdelegates#1]
Basically that...

I am trying to use your library in this project which is doing the Weak Event pattern using the old `WeakEventManager`.

So, code like this: 
`WeakEventManager<DataTable, DataRowChangeEventArgs>.AddHandler(_dset.tbl, "RowChanged", tbl_RowChanged);`

Would basically, translate to:

`_dset.tbl.RowChanged += WeakDelegates.WeakDelegate.Combine<DataRowChangeEventHandler>(null, tbl_RowChanged);`

However, I am not entirely sure on how to remove the handler. Before, I would do:

`WeakEventManager<DataTable, DataRowChangeEventArgs>.RemoveHandler(_dset.tbl, "RowChanged", tbl_RowChanged);`

Would this be the correct way?:

`_dset.tbl.RowChanged -= WeakDelegates.WeakDelegate.Remove<DataRowChangeEventHandler>(tbl_RowChanged, null);`

Thanks

**Comment by shmuelie** [comment]
Hi!

Sadly there isn't really a good way to unsubscribe from an event outside the class of the event since it needs access to the delegate back the event. I can play around with making some code to allow for this but as is there's no real way to do it.

**Comment by lumalav** [comment]
Oh I see. Thanks for the reply though!

**Comment by shmuelie** [comment]
@lumalav just pushed new code that not only adds what you need but fixes some bugs I found!

**Comment by lumalav** [comment]
Awesome @shmuelie. Just tested it and works perfectly. Thanks!
